api = "0.9"

[buildpack]
id = "portersupport/heroku-buildpack-awscli"
version = "0.1.0"
name = "Heroku Buildpack AWS CLI"
homepage = "https://github.com/weibeld/heroku-buildpack-awscli"

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
